// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.jflavan.pulumi.osano.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetCookieConsentRulesArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetCookieConsentRulesArgs Empty = new GetCookieConsentRulesArgs();

    /**
     * Only return rules with this classification: ANALYTICS, BLACKLISTED, ESSENTIAL, HIDDEN, MARKETING, PERSONALIZATION.
     *
     */
    @Import(name="classification")
    private @Nullable Output<String> classification;

    /**
     * @return Only return rules with this classification: ANALYTICS, BLACKLISTED, ESSENTIAL, HIDDEN, MARKETING, PERSONALIZATION.
     *
     */
    public Optional<Output<String>> classification() {
        return Optional.ofNullable(this.classification);
    }

    /**
     * The Osano Cookie Consent config ID whose rules are listed.
     *
     */
    @Import(name="configId", required=true)
    private Output<String> configId;

    /**
     * @return The Osano Cookie Consent config ID whose rules are listed.
     *
     */
    public Output<String> configId() {
        return this.configId;
    }

    /**
     * Stop after this many rules. Unset or 0 returns every matching rule.
     *
     */
    @Import(name="maxResults")
    private @Nullable Output<Integer> maxResults;

    /**
     * @return Stop after this many rules. Unset or 0 returns every matching rule.
     *
     */
    public Optional<Output<Integer>> maxResults() {
        return Optional.ofNullable(this.maxResults);
    }

    /**
     * Only return rules of this storage type: cookies, scripts, iframes, localStorage.
     *
     */
    @Import(name="storeType")
    private @Nullable Output<String> storeType;

    /**
     * @return Only return rules of this storage type: cookies, scripts, iframes, localStorage.
     *
     */
    public Optional<Output<String>> storeType() {
        return Optional.ofNullable(this.storeType);
    }

    private GetCookieConsentRulesArgs() {}

    private GetCookieConsentRulesArgs(GetCookieConsentRulesArgs $) {
        this.classification = $.classification;
        this.configId = $.configId;
        this.maxResults = $.maxResults;
        this.storeType = $.storeType;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetCookieConsentRulesArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetCookieConsentRulesArgs $;

        public Builder() {
            $ = new GetCookieConsentRulesArgs();
        }

        public Builder(GetCookieConsentRulesArgs defaults) {
            $ = new GetCookieConsentRulesArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param classification Only return rules with this classification: ANALYTICS, BLACKLISTED, ESSENTIAL, HIDDEN, MARKETING, PERSONALIZATION.
         *
         * @return builder
         *
         */
        public Builder classification(@Nullable Output<String> classification) {
            $.classification = classification;
            return this;
        }

        /**
         * @param classification Only return rules with this classification: ANALYTICS, BLACKLISTED, ESSENTIAL, HIDDEN, MARKETING, PERSONALIZATION.
         *
         * @return builder
         *
         */
        public Builder classification(String classification) {
            return classification(Output.of(classification));
        }

        /**
         * @param configId The Osano Cookie Consent config ID whose rules are listed.
         *
         * @return builder
         *
         */
        public Builder configId(Output<String> configId) {
            $.configId = configId;
            return this;
        }

        /**
         * @param configId The Osano Cookie Consent config ID whose rules are listed.
         *
         * @return builder
         *
         */
        public Builder configId(String configId) {
            return configId(Output.of(configId));
        }

        /**
         * @param maxResults Stop after this many rules. Unset or 0 returns every matching rule.
         *
         * @return builder
         *
         */
        public Builder maxResults(@Nullable Output<Integer> maxResults) {
            $.maxResults = maxResults;
            return this;
        }

        /**
         * @param maxResults Stop after this many rules. Unset or 0 returns every matching rule.
         *
         * @return builder
         *
         */
        public Builder maxResults(Integer maxResults) {
            return maxResults(Output.of(maxResults));
        }

        /**
         * @param storeType Only return rules of this storage type: cookies, scripts, iframes, localStorage.
         *
         * @return builder
         *
         */
        public Builder storeType(@Nullable Output<String> storeType) {
            $.storeType = storeType;
            return this;
        }

        /**
         * @param storeType Only return rules of this storage type: cookies, scripts, iframes, localStorage.
         *
         * @return builder
         *
         */
        public Builder storeType(String storeType) {
            return storeType(Output.of(storeType));
        }

        public GetCookieConsentRulesArgs build() {
            if ($.configId == null) {
                throw new MissingRequiredPropertyException("GetCookieConsentRulesArgs", "configId");
            }
            return $;
        }
    }

}
