// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Immutable;

namespace Community.Pulumi.Osano
{
    public static class Config
    {
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "IDE1006", Justification = 
        "Double underscore prefix used to avoid conflicts with variable names.")]
        private sealed class __Value<T>
        {
            private readonly Func<T> _getter;
            private T _value = default!;
            private bool _set;

            public __Value(Func<T> getter)
            {
                _getter = getter;
            }

            public T Get() => _set ? _value : _getter();

            public void Set(T value)
            {
                _value = value;
                _set = true;
            }
        }

        private static readonly global::Pulumi.Config __config = new global::Pulumi.Config("osano");

        private static readonly __Value<string?> _apiBaseUrl = new __Value<string?>(() => __config.Get("apiBaseUrl"));
        /// <summary>
        /// Base URL of the Unified Consent API, including any path prefix (default https://uc.api.osano.com). The OSANO_API_BASE_URL environment variable is used when it is unset. Must use https, except for loopback hosts.
        /// </summary>
        public static string? ApiBaseUrl
        {
            get => _apiBaseUrl.Get();
            set => _apiBaseUrl.Set(value);
        }

        private static readonly __Value<string?> _customerBaseUrl = new __Value<string?>(() => __config.Get("customerBaseUrl"));
        /// <summary>
        /// Base URL of the Customer REST API (default https://api.osano.com). The OSANO_CUSTOMER_BASE_URL environment variable is used when it is unset. Must use https, except for loopback hosts.
        /// </summary>
        public static string? CustomerBaseUrl
        {
            get => _customerBaseUrl.Get();
            set => _customerBaseUrl.Set(value);
        }

        private static readonly __Value<string?> _osanoApiKey = new __Value<string?>(() => __config.Get("osanoApiKey"));
        /// <summary>
        /// Osano Customer REST API key, sent as x-osano-api-key by the Cookie Consent resources and functions and by sendSubjectCode and verifySubjectCode. Set it with `pulumi config set osano:osanoApiKey --secret`; the OSANO_API_KEY environment variable is used when it is unset.
        /// </summary>
        public static string? OsanoApiKey
        {
            get => _osanoApiKey.Get();
            set => _osanoApiKey.Set(value);
        }

        private static readonly __Value<int?> _requestTimeoutSeconds = new __Value<int?>(() => __config.GetInt32("requestTimeoutSeconds"));
        /// <summary>
        /// Timeout in seconds for each HTTP request attempt to the Osano APIs, from 1 to 3600 (default 60). Retried requests wait for each attempt separately. The OSANO_API_TIMEOUT_SECONDS environment variable is used when it is unset.
        /// </summary>
        public static int? RequestTimeoutSeconds
        {
            get => _requestTimeoutSeconds.Get();
            set => _requestTimeoutSeconds.Set(value);
        }

        private static readonly __Value<string?> _ucApiKey = new __Value<string?>(() => __config.Get("ucApiKey"));
        /// <summary>
        /// Former name of unifiedConsentApiKey, read only when that key is unset.
        /// </summary>
        public static string? UcApiKey
        {
            get => _ucApiKey.Get();
            set => _ucApiKey.Set(value);
        }

        private static readonly __Value<string?> _ucBaseUrl = new __Value<string?>(() => __config.Get("ucBaseUrl"));
        /// <summary>
        /// Former name of apiBaseUrl, read only when apiBaseUrl is unset.
        /// </summary>
        public static string? UcBaseUrl
        {
            get => _ucBaseUrl.Get();
            set => _ucBaseUrl.Set(value);
        }

        private static readonly __Value<string?> _unifiedConsentApiKey = new __Value<string?>(() => __config.Get("unifiedConsentApiKey"));
        /// <summary>
        /// Unified Consent API key, sent as x-uc-api-key by the Consent resource and the Unified Consent functions. Set it with `pulumi config set osano:unifiedConsentApiKey --secret`; the OSANO_UC_API_KEY environment variable is used when it is unset.
        /// </summary>
        public static string? UnifiedConsentApiKey
        {
            get => _unifiedConsentApiKey.Get();
            set => _unifiedConsentApiKey.Set(value);
        }

    }
}
