// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/jflavan/pulumi-osano/sdk/go/osano/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

var _ = internal.GetEnvOrDefault

// Base URL of the Unified Consent API, including any path prefix (default https://uc.api.osano.com). The OSANO_API_BASE_URL environment variable is used when it is unset. Must use https, except for loopback hosts.
func GetApiBaseUrl(ctx *pulumi.Context) string {
	return config.Get(ctx, "osano:apiBaseUrl")
}

// Base URL of the Customer REST API (default https://api.osano.com). The OSANO_CUSTOMER_BASE_URL environment variable is used when it is unset. Must use https, except for loopback hosts.
func GetCustomerBaseUrl(ctx *pulumi.Context) string {
	return config.Get(ctx, "osano:customerBaseUrl")
}

// Osano Customer REST API key, sent as x-osano-api-key by the Cookie Consent resources and functions and by sendSubjectCode and verifySubjectCode. Set it with `pulumi config set osano:osanoApiKey --secret`; the OSANO_API_KEY environment variable is used when it is unset.
func GetOsanoApiKey(ctx *pulumi.Context) string {
	return config.Get(ctx, "osano:osanoApiKey")
}

// Timeout in seconds for each HTTP request attempt to the Osano APIs, from 1 to 3600 (default 60). Retried requests wait for each attempt separately. The OSANO_API_TIMEOUT_SECONDS environment variable is used when it is unset.
func GetRequestTimeoutSeconds(ctx *pulumi.Context) int {
	return config.GetInt(ctx, "osano:requestTimeoutSeconds")
}

// Former name of unifiedConsentApiKey, read only when that key is unset.
//
// Deprecated: use unifiedConsentApiKey instead
func GetUcApiKey(ctx *pulumi.Context) string {
	return config.Get(ctx, "osano:ucApiKey")
}

// Former name of apiBaseUrl, read only when apiBaseUrl is unset.
//
// Deprecated: use apiBaseUrl instead
func GetUcBaseUrl(ctx *pulumi.Context) string {
	return config.Get(ctx, "osano:ucBaseUrl")
}

// Unified Consent API key, sent as x-uc-api-key by the Consent resource and the Unified Consent functions. Set it with `pulumi config set osano:unifiedConsentApiKey --secret`; the OSANO_UC_API_KEY environment variable is used when it is unset.
func GetUnifiedConsentApiKey(ctx *pulumi.Context) string {
	return config.Get(ctx, "osano:unifiedConsentApiKey")
}
