// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Community.Pulumi.Osano.Outputs
{

    /// <summary>
    /// The subject a consent is recorded for, identified by a verified ID or an anonymous ID.
    /// </summary>
    [OutputType]
    public sealed class ConsentSubject
    {
        /// <summary>
        /// The subject's anonymous ID. Must not contain #, %, or spaces.
        /// </summary>
        public readonly string? AnonymousId;
        /// <summary>
        /// The subject's verified ID. Must not contain #, %, or spaces.
        /// </summary>
        public readonly string? VerifiedId;

        [OutputConstructor]
        private ConsentSubject(
            string? anonymousId,

            string? verifiedId)
        {
            AnonymousId = anonymousId;
            VerifiedId = verifiedId;
        }
    }
}
