// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.jflavan.pulumi.osano;

import com.pulumi.core.internal.Codegen;
import java.lang.Integer;
import java.lang.String;
import java.util.Optional;

public final class Config {

    private static final com.pulumi.Config config = com.pulumi.Config.of("osano");
/**
 * Base URL of the Unified Consent API, including any path prefix (default https://uc.api.osano.com). The OSANO_API_BASE_URL environment variable is used when it is unset. Must use https, except for loopback hosts.
 *
 */
    public Optional<String> apiBaseUrl() {
        return Codegen.stringProp("apiBaseUrl").config(config).get();
    }
/**
 * Base URL of the Customer REST API (default https://api.osano.com). The OSANO_CUSTOMER_BASE_URL environment variable is used when it is unset. Must use https, except for loopback hosts.
 *
 */
    public Optional<String> customerBaseUrl() {
        return Codegen.stringProp("customerBaseUrl").config(config).get();
    }
/**
 * Osano Customer REST API key, sent as x-osano-api-key by the Cookie Consent resources and functions and by sendSubjectCode and verifySubjectCode. Set it with `pulumi config set osano:osanoApiKey --secret`; the OSANO_API_KEY environment variable is used when it is unset.
 *
 */
    public Optional<String> osanoApiKey() {
        return Codegen.stringProp("osanoApiKey").config(config).get();
    }
/**
 * Timeout in seconds for each HTTP request attempt to the Osano APIs, from 1 to 3600 (default 60). Retried requests wait for each attempt separately. The OSANO_API_TIMEOUT_SECONDS environment variable is used when it is unset.
 *
 */
    public Optional<Integer> requestTimeoutSeconds() {
        return Codegen.integerProp("requestTimeoutSeconds").config(config).get();
    }
/**
 * Former name of unifiedConsentApiKey, read only when that key is unset.
 *
 */
    public Optional<String> ucApiKey() {
        return Codegen.stringProp("ucApiKey").config(config).get();
    }
/**
 * Former name of apiBaseUrl, read only when apiBaseUrl is unset.
 *
 */
    public Optional<String> ucBaseUrl() {
        return Codegen.stringProp("ucBaseUrl").config(config).get();
    }
/**
 * Unified Consent API key, sent as x-uc-api-key by the Consent resource and the Unified Consent functions. Set it with `pulumi config set osano:unifiedConsentApiKey --secret`; the OSANO_UC_API_KEY environment variable is used when it is unset.
 *
 */
    public Optional<String> unifiedConsentApiKey() {
        return Codegen.stringProp("unifiedConsentApiKey").config(config).get();
    }
}
