// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.jflavan.pulumi.osano;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ProviderArgs extends com.pulumi.resources.ResourceArgs {

    public static final ProviderArgs Empty = new ProviderArgs();

    /**
     * Base URL of the Unified Consent API, including any path prefix (default https://uc.api.osano.com). The OSANO_API_BASE_URL environment variable is used when it is unset. Must use https, except for loopback hosts.
     *
     */
    @Import(name="apiBaseUrl")
    private @Nullable Output<String> apiBaseUrl;

    /**
     * @return Base URL of the Unified Consent API, including any path prefix (default https://uc.api.osano.com). The OSANO_API_BASE_URL environment variable is used when it is unset. Must use https, except for loopback hosts.
     *
     */
    public Optional<Output<String>> apiBaseUrl() {
        return Optional.ofNullable(this.apiBaseUrl);
    }

    /**
     * Base URL of the Customer REST API (default https://api.osano.com). The OSANO_CUSTOMER_BASE_URL environment variable is used when it is unset. Must use https, except for loopback hosts.
     *
     */
    @Import(name="customerBaseUrl")
    private @Nullable Output<String> customerBaseUrl;

    /**
     * @return Base URL of the Customer REST API (default https://api.osano.com). The OSANO_CUSTOMER_BASE_URL environment variable is used when it is unset. Must use https, except for loopback hosts.
     *
     */
    public Optional<Output<String>> customerBaseUrl() {
        return Optional.ofNullable(this.customerBaseUrl);
    }

    /**
     * Osano Customer REST API key, sent as x-osano-api-key by the Cookie Consent resources and functions and by sendSubjectCode and verifySubjectCode. Set it with `pulumi config set osano:osanoApiKey --secret`; the OSANO_API_KEY environment variable is used when it is unset.
     *
     */
    @Import(name="osanoApiKey")
    private @Nullable Output<String> osanoApiKey;

    /**
     * @return Osano Customer REST API key, sent as x-osano-api-key by the Cookie Consent resources and functions and by sendSubjectCode and verifySubjectCode. Set it with `pulumi config set osano:osanoApiKey --secret`; the OSANO_API_KEY environment variable is used when it is unset.
     *
     */
    public Optional<Output<String>> osanoApiKey() {
        return Optional.ofNullable(this.osanoApiKey);
    }

    /**
     * Timeout in seconds for each HTTP request attempt to the Osano APIs, from 1 to 3600 (default 60). Retried requests wait for each attempt separately. The OSANO_API_TIMEOUT_SECONDS environment variable is used when it is unset.
     *
     */
    @Import(name="requestTimeoutSeconds", json=true)
    private @Nullable Output<Integer> requestTimeoutSeconds;

    /**
     * @return Timeout in seconds for each HTTP request attempt to the Osano APIs, from 1 to 3600 (default 60). Retried requests wait for each attempt separately. The OSANO_API_TIMEOUT_SECONDS environment variable is used when it is unset.
     *
     */
    public Optional<Output<Integer>> requestTimeoutSeconds() {
        return Optional.ofNullable(this.requestTimeoutSeconds);
    }

    /**
     * Former name of unifiedConsentApiKey, read only when that key is unset.
     *
     * @deprecated
     * use unifiedConsentApiKey instead
     *
     */
    @Deprecated /* use unifiedConsentApiKey instead */
    @Import(name="ucApiKey")
    private @Nullable Output<String> ucApiKey;

    /**
     * @return Former name of unifiedConsentApiKey, read only when that key is unset.
     *
     * @deprecated
     * use unifiedConsentApiKey instead
     *
     */
    @Deprecated /* use unifiedConsentApiKey instead */
    public Optional<Output<String>> ucApiKey() {
        return Optional.ofNullable(this.ucApiKey);
    }

    /**
     * Former name of apiBaseUrl, read only when apiBaseUrl is unset.
     *
     * @deprecated
     * use apiBaseUrl instead
     *
     */
    @Deprecated /* use apiBaseUrl instead */
    @Import(name="ucBaseUrl")
    private @Nullable Output<String> ucBaseUrl;

    /**
     * @return Former name of apiBaseUrl, read only when apiBaseUrl is unset.
     *
     * @deprecated
     * use apiBaseUrl instead
     *
     */
    @Deprecated /* use apiBaseUrl instead */
    public Optional<Output<String>> ucBaseUrl() {
        return Optional.ofNullable(this.ucBaseUrl);
    }

    /**
     * Unified Consent API key, sent as x-uc-api-key by the Consent resource and the Unified Consent functions. Set it with `pulumi config set osano:unifiedConsentApiKey --secret`; the OSANO_UC_API_KEY environment variable is used when it is unset.
     *
     */
    @Import(name="unifiedConsentApiKey")
    private @Nullable Output<String> unifiedConsentApiKey;

    /**
     * @return Unified Consent API key, sent as x-uc-api-key by the Consent resource and the Unified Consent functions. Set it with `pulumi config set osano:unifiedConsentApiKey --secret`; the OSANO_UC_API_KEY environment variable is used when it is unset.
     *
     */
    public Optional<Output<String>> unifiedConsentApiKey() {
        return Optional.ofNullable(this.unifiedConsentApiKey);
    }

    private ProviderArgs() {}

    private ProviderArgs(ProviderArgs $) {
        this.apiBaseUrl = $.apiBaseUrl;
        this.customerBaseUrl = $.customerBaseUrl;
        this.osanoApiKey = $.osanoApiKey;
        this.requestTimeoutSeconds = $.requestTimeoutSeconds;
        this.ucApiKey = $.ucApiKey;
        this.ucBaseUrl = $.ucBaseUrl;
        this.unifiedConsentApiKey = $.unifiedConsentApiKey;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ProviderArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ProviderArgs $;

        public Builder() {
            $ = new ProviderArgs();
        }

        public Builder(ProviderArgs defaults) {
            $ = new ProviderArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param apiBaseUrl Base URL of the Unified Consent API, including any path prefix (default https://uc.api.osano.com). The OSANO_API_BASE_URL environment variable is used when it is unset. Must use https, except for loopback hosts.
         *
         * @return builder
         *
         */
        public Builder apiBaseUrl(@Nullable Output<String> apiBaseUrl) {
            $.apiBaseUrl = apiBaseUrl;
            return this;
        }

        /**
         * @param apiBaseUrl Base URL of the Unified Consent API, including any path prefix (default https://uc.api.osano.com). The OSANO_API_BASE_URL environment variable is used when it is unset. Must use https, except for loopback hosts.
         *
         * @return builder
         *
         */
        public Builder apiBaseUrl(String apiBaseUrl) {
            return apiBaseUrl(Output.of(apiBaseUrl));
        }

        /**
         * @param customerBaseUrl Base URL of the Customer REST API (default https://api.osano.com). The OSANO_CUSTOMER_BASE_URL environment variable is used when it is unset. Must use https, except for loopback hosts.
         *
         * @return builder
         *
         */
        public Builder customerBaseUrl(@Nullable Output<String> customerBaseUrl) {
            $.customerBaseUrl = customerBaseUrl;
            return this;
        }

        /**
         * @param customerBaseUrl Base URL of the Customer REST API (default https://api.osano.com). The OSANO_CUSTOMER_BASE_URL environment variable is used when it is unset. Must use https, except for loopback hosts.
         *
         * @return builder
         *
         */
        public Builder customerBaseUrl(String customerBaseUrl) {
            return customerBaseUrl(Output.of(customerBaseUrl));
        }

        /**
         * @param osanoApiKey Osano Customer REST API key, sent as x-osano-api-key by the Cookie Consent resources and functions and by sendSubjectCode and verifySubjectCode. Set it with `pulumi config set osano:osanoApiKey --secret`; the OSANO_API_KEY environment variable is used when it is unset.
         *
         * @return builder
         *
         */
        public Builder osanoApiKey(@Nullable Output<String> osanoApiKey) {
            $.osanoApiKey = osanoApiKey;
            return this;
        }

        /**
         * @param osanoApiKey Osano Customer REST API key, sent as x-osano-api-key by the Cookie Consent resources and functions and by sendSubjectCode and verifySubjectCode. Set it with `pulumi config set osano:osanoApiKey --secret`; the OSANO_API_KEY environment variable is used when it is unset.
         *
         * @return builder
         *
         */
        public Builder osanoApiKey(String osanoApiKey) {
            return osanoApiKey(Output.of(osanoApiKey));
        }

        /**
         * @param requestTimeoutSeconds Timeout in seconds for each HTTP request attempt to the Osano APIs, from 1 to 3600 (default 60). Retried requests wait for each attempt separately. The OSANO_API_TIMEOUT_SECONDS environment variable is used when it is unset.
         *
         * @return builder
         *
         */
        public Builder requestTimeoutSeconds(@Nullable Output<Integer> requestTimeoutSeconds) {
            $.requestTimeoutSeconds = requestTimeoutSeconds;
            return this;
        }

        /**
         * @param requestTimeoutSeconds Timeout in seconds for each HTTP request attempt to the Osano APIs, from 1 to 3600 (default 60). Retried requests wait for each attempt separately. The OSANO_API_TIMEOUT_SECONDS environment variable is used when it is unset.
         *
         * @return builder
         *
         */
        public Builder requestTimeoutSeconds(Integer requestTimeoutSeconds) {
            return requestTimeoutSeconds(Output.of(requestTimeoutSeconds));
        }

        /**
         * @param ucApiKey Former name of unifiedConsentApiKey, read only when that key is unset.
         *
         * @return builder
         *
         * @deprecated
         * use unifiedConsentApiKey instead
         *
         */
        @Deprecated /* use unifiedConsentApiKey instead */
        public Builder ucApiKey(@Nullable Output<String> ucApiKey) {
            $.ucApiKey = ucApiKey;
            return this;
        }

        /**
         * @param ucApiKey Former name of unifiedConsentApiKey, read only when that key is unset.
         *
         * @return builder
         *
         * @deprecated
         * use unifiedConsentApiKey instead
         *
         */
        @Deprecated /* use unifiedConsentApiKey instead */
        public Builder ucApiKey(String ucApiKey) {
            return ucApiKey(Output.of(ucApiKey));
        }

        /**
         * @param ucBaseUrl Former name of apiBaseUrl, read only when apiBaseUrl is unset.
         *
         * @return builder
         *
         * @deprecated
         * use apiBaseUrl instead
         *
         */
        @Deprecated /* use apiBaseUrl instead */
        public Builder ucBaseUrl(@Nullable Output<String> ucBaseUrl) {
            $.ucBaseUrl = ucBaseUrl;
            return this;
        }

        /**
         * @param ucBaseUrl Former name of apiBaseUrl, read only when apiBaseUrl is unset.
         *
         * @return builder
         *
         * @deprecated
         * use apiBaseUrl instead
         *
         */
        @Deprecated /* use apiBaseUrl instead */
        public Builder ucBaseUrl(String ucBaseUrl) {
            return ucBaseUrl(Output.of(ucBaseUrl));
        }

        /**
         * @param unifiedConsentApiKey Unified Consent API key, sent as x-uc-api-key by the Consent resource and the Unified Consent functions. Set it with `pulumi config set osano:unifiedConsentApiKey --secret`; the OSANO_UC_API_KEY environment variable is used when it is unset.
         *
         * @return builder
         *
         */
        public Builder unifiedConsentApiKey(@Nullable Output<String> unifiedConsentApiKey) {
            $.unifiedConsentApiKey = unifiedConsentApiKey;
            return this;
        }

        /**
         * @param unifiedConsentApiKey Unified Consent API key, sent as x-uc-api-key by the Consent resource and the Unified Consent functions. Set it with `pulumi config set osano:unifiedConsentApiKey --secret`; the OSANO_UC_API_KEY environment variable is used when it is unset.
         *
         * @return builder
         *
         */
        public Builder unifiedConsentApiKey(String unifiedConsentApiKey) {
            return unifiedConsentApiKey(Output.of(unifiedConsentApiKey));
        }

        public ProviderArgs build() {
            return $;
        }
    }

}
