// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.jflavan.pulumi.osano;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import io.github.jflavan.pulumi.osano.ProviderArgs;
import io.github.jflavan.pulumi.osano.Utilities;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import javax.annotation.Nullable;

@ResourceType(type="pulumi:providers:osano")
public class Provider extends com.pulumi.resources.ProviderResource {
    /**
     * Base URL of the Unified Consent API, including any path prefix (default https://uc.api.osano.com). The OSANO_API_BASE_URL environment variable is used when it is unset. Must use https, except for loopback hosts.
     *
     */
    @Export(name="apiBaseUrl", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> apiBaseUrl;

    /**
     * @return Base URL of the Unified Consent API, including any path prefix (default https://uc.api.osano.com). The OSANO_API_BASE_URL environment variable is used when it is unset. Must use https, except for loopback hosts.
     *
     */
    public Output<Optional<String>> apiBaseUrl() {
        return Codegen.optional(this.apiBaseUrl);
    }
    /**
     * Base URL of the Customer REST API (default https://api.osano.com). The OSANO_CUSTOMER_BASE_URL environment variable is used when it is unset. Must use https, except for loopback hosts.
     *
     */
    @Export(name="customerBaseUrl", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> customerBaseUrl;

    /**
     * @return Base URL of the Customer REST API (default https://api.osano.com). The OSANO_CUSTOMER_BASE_URL environment variable is used when it is unset. Must use https, except for loopback hosts.
     *
     */
    public Output<Optional<String>> customerBaseUrl() {
        return Codegen.optional(this.customerBaseUrl);
    }
    /**
     * Osano Customer REST API key, sent as x-osano-api-key by the Cookie Consent resources and functions and by sendSubjectCode and verifySubjectCode. Set it with `pulumi config set osano:osanoApiKey --secret`; the OSANO_API_KEY environment variable is used when it is unset.
     *
     */
    @Export(name="osanoApiKey", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> osanoApiKey;

    /**
     * @return Osano Customer REST API key, sent as x-osano-api-key by the Cookie Consent resources and functions and by sendSubjectCode and verifySubjectCode. Set it with `pulumi config set osano:osanoApiKey --secret`; the OSANO_API_KEY environment variable is used when it is unset.
     *
     */
    public Output<Optional<String>> osanoApiKey() {
        return Codegen.optional(this.osanoApiKey);
    }
    /**
     * Former name of unifiedConsentApiKey, read only when that key is unset.
     *
     * @deprecated
     * use unifiedConsentApiKey instead
     *
     */
    @Deprecated /* use unifiedConsentApiKey instead */
    @Export(name="ucApiKey", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> ucApiKey;

    /**
     * @return Former name of unifiedConsentApiKey, read only when that key is unset.
     *
     */
    public Output<Optional<String>> ucApiKey() {
        return Codegen.optional(this.ucApiKey);
    }
    /**
     * Former name of apiBaseUrl, read only when apiBaseUrl is unset.
     *
     * @deprecated
     * use apiBaseUrl instead
     *
     */
    @Deprecated /* use apiBaseUrl instead */
    @Export(name="ucBaseUrl", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> ucBaseUrl;

    /**
     * @return Former name of apiBaseUrl, read only when apiBaseUrl is unset.
     *
     */
    public Output<Optional<String>> ucBaseUrl() {
        return Codegen.optional(this.ucBaseUrl);
    }
    /**
     * Unified Consent API key, sent as x-uc-api-key by the Consent resource and the Unified Consent functions. Set it with `pulumi config set osano:unifiedConsentApiKey --secret`; the OSANO_UC_API_KEY environment variable is used when it is unset.
     *
     */
    @Export(name="unifiedConsentApiKey", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> unifiedConsentApiKey;

    /**
     * @return Unified Consent API key, sent as x-uc-api-key by the Consent resource and the Unified Consent functions. Set it with `pulumi config set osano:unifiedConsentApiKey --secret`; the OSANO_UC_API_KEY environment variable is used when it is unset.
     *
     */
    public Output<Optional<String>> unifiedConsentApiKey() {
        return Codegen.optional(this.unifiedConsentApiKey);
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public Provider(java.lang.String name) {
        this(name, ProviderArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public Provider(java.lang.String name, @Nullable ProviderArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public Provider(java.lang.String name, @Nullable ProviderArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("osano", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private static ProviderArgs makeArgs(@Nullable ProviderArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? ProviderArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .pluginDownloadURL("github://api.github.com/jflavan/pulumi-osano")
            .additionalSecretOutputs(List.of(
                "osanoApiKey",
                "ucApiKey",
                "unifiedConsentApiKey"
            ))
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

}
