// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

declare var exports: any;
const __config = new pulumi.Config("osano");

/**
 * Base URL of the Unified Consent API, including any path prefix (default https://uc.api.osano.com). The OSANO_API_BASE_URL environment variable is used when it is unset. Must use https, except for loopback hosts.
 */
export declare const apiBaseUrl: string | undefined;
Object.defineProperty(exports, "apiBaseUrl", {
    get() {
        return __config.get("apiBaseUrl");
    },
    enumerable: true,
});

/**
 * Base URL of the Customer REST API (default https://api.osano.com). The OSANO_CUSTOMER_BASE_URL environment variable is used when it is unset. Must use https, except for loopback hosts.
 */
export declare const customerBaseUrl: string | undefined;
Object.defineProperty(exports, "customerBaseUrl", {
    get() {
        return __config.get("customerBaseUrl");
    },
    enumerable: true,
});

/**
 * Osano Customer REST API key, sent as x-osano-api-key by the Cookie Consent resources and functions and by sendSubjectCode and verifySubjectCode. Set it with `pulumi config set osano:osanoApiKey --secret`; the OSANO_API_KEY environment variable is used when it is unset.
 */
export declare const osanoApiKey: string | undefined;
Object.defineProperty(exports, "osanoApiKey", {
    get() {
        return __config.get("osanoApiKey");
    },
    enumerable: true,
});

/**
 * Timeout in seconds for each HTTP request attempt to the Osano APIs, from 1 to 3600 (default 60). Retried requests wait for each attempt separately. The OSANO_API_TIMEOUT_SECONDS environment variable is used when it is unset.
 */
export declare const requestTimeoutSeconds: number | undefined;
Object.defineProperty(exports, "requestTimeoutSeconds", {
    get() {
        return __config.getObject<number>("requestTimeoutSeconds");
    },
    enumerable: true,
});

/**
 * Former name of unifiedConsentApiKey, read only when that key is unset.
 */
export declare const ucApiKey: string | undefined;
Object.defineProperty(exports, "ucApiKey", {
    get() {
        return __config.get("ucApiKey");
    },
    enumerable: true,
});

/**
 * Former name of apiBaseUrl, read only when apiBaseUrl is unset.
 */
export declare const ucBaseUrl: string | undefined;
Object.defineProperty(exports, "ucBaseUrl", {
    get() {
        return __config.get("ucBaseUrl");
    },
    enumerable: true,
});

/**
 * Unified Consent API key, sent as x-uc-api-key by the Consent resource and the Unified Consent functions. Set it with `pulumi config set osano:unifiedConsentApiKey --secret`; the OSANO_UC_API_KEY environment variable is used when it is unset.
 */
export declare const unifiedConsentApiKey: string | undefined;
Object.defineProperty(exports, "unifiedConsentApiKey", {
    get() {
        return __config.get("unifiedConsentApiKey");
    },
    enumerable: true,
});

