// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Community.Pulumi.Osano
{
    public static class CheckConsent
    {
        /// <summary>
        /// Checks whether a unified consent record exists for a given subject ID.
        /// </summary>
        public static Task<CheckConsentResult> InvokeAsync(CheckConsentArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<CheckConsentResult>("osano:index:checkConsent", args ?? new CheckConsentArgs(), options.WithDefaults());

        /// <summary>
        /// Checks whether a unified consent record exists for a given subject ID.
        /// </summary>
        public static Output<CheckConsentResult> Invoke(CheckConsentInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<CheckConsentResult>("osano:index:checkConsent", args ?? new CheckConsentInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// Checks whether a unified consent record exists for a given subject ID.
        /// </summary>
        public static Output<CheckConsentResult> Invoke(CheckConsentInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<CheckConsentResult>("osano:index:checkConsent", args ?? new CheckConsentInvokeArgs(), options.WithDefaults());
    }


    public sealed class CheckConsentArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Optional ISO 3166-1 country code Osano uses instead of resolving the caller's IP address, which in a pipeline is the CI runner's.
        /// </summary>
        [Input("countryCodeOverride")]
        public string? CountryCodeOverride { get; set; }

        /// <summary>
        /// Optional ISO 3166-2 region code Osano uses instead of resolving the caller's IP address.
        /// </summary>
        [Input("regionCodeOverride")]
        public string? RegionCodeOverride { get; set; }

        [Input("subjectId", required: true)]
        private string? _subjectId;

        /// <summary>
        /// The subject ID to check. Secret, because it identifies a person.
        /// </summary>
        public string? SubjectId
        {
            get => _subjectId;
            set => _subjectId = value;
        }

        public CheckConsentArgs()
        {
        }
        public static new CheckConsentArgs Empty => new CheckConsentArgs();
    }

    public sealed class CheckConsentInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Optional ISO 3166-1 country code Osano uses instead of resolving the caller's IP address, which in a pipeline is the CI runner's.
        /// </summary>
        [Input("countryCodeOverride")]
        public Input<string>? CountryCodeOverride { get; set; }

        /// <summary>
        /// Optional ISO 3166-2 region code Osano uses instead of resolving the caller's IP address.
        /// </summary>
        [Input("regionCodeOverride")]
        public Input<string>? RegionCodeOverride { get; set; }

        [Input("subjectId", required: true)]
        private Input<string>? _subjectId;

        /// <summary>
        /// The subject ID to check. Secret, because it identifies a person.
        /// </summary>
        public Input<string>? SubjectId
        {
            get => _subjectId;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _subjectId = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        public CheckConsentInvokeArgs()
        {
        }
        public static new CheckConsentInvokeArgs Empty => new CheckConsentInvokeArgs();
    }


    [OutputType]
    public sealed class CheckConsentResult
    {
        /// <summary>
        /// Whether the subject has given consent in the configuration.
        /// </summary>
        public readonly bool Exists;
        /// <summary>
        /// The subject ID that was checked. Secret, because it identifies a person.
        /// </summary>
        public readonly string SubjectId;

        [OutputConstructor]
        private CheckConsentResult(
            bool exists,

            string subjectId)
        {
            Exists = exists;
            SubjectId = subjectId;
        }
    }
}
