// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Community.Pulumi.Osano
{
    public static class GetSubject
    {
        /// <summary>
        /// Fetches subject identifiers (subject, verified, anonymous IDs) for a reference or session ID.
        /// </summary>
        public static Task<GetSubjectResult> InvokeAsync(GetSubjectArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetSubjectResult>("osano:index:getSubject", args ?? new GetSubjectArgs(), options.WithDefaults());

        /// <summary>
        /// Fetches subject identifiers (subject, verified, anonymous IDs) for a reference or session ID.
        /// </summary>
        public static Output<GetSubjectResult> Invoke(GetSubjectInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetSubjectResult>("osano:index:getSubject", args ?? new GetSubjectInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// Fetches subject identifiers (subject, verified, anonymous IDs) for a reference or session ID.
        /// </summary>
        public static Output<GetSubjectResult> Invoke(GetSubjectInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetSubjectResult>("osano:index:getSubject", args ?? new GetSubjectInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetSubjectArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Reference type: subject (default) for a subject's verified or anonymous ID, or session for a session ID. anonymous is accepted as a deprecated alias of subject.
        /// </summary>
        [Input("referenceType")]
        public string? ReferenceType { get; set; }

        [Input("subjectRef", required: true)]
        private string? _subjectRef;

        /// <summary>
        /// The subject reference to resolve: an anonymous ID, verified ID, or session ID.
        /// </summary>
        public string? SubjectRef
        {
            get => _subjectRef;
            set => _subjectRef = value;
        }

        public GetSubjectArgs()
        {
        }
        public static new GetSubjectArgs Empty => new GetSubjectArgs();
    }

    public sealed class GetSubjectInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Reference type: subject (default) for a subject's verified or anonymous ID, or session for a session ID. anonymous is accepted as a deprecated alias of subject.
        /// </summary>
        [Input("referenceType")]
        public Input<string>? ReferenceType { get; set; }

        [Input("subjectRef", required: true)]
        private Input<string>? _subjectRef;

        /// <summary>
        /// The subject reference to resolve: an anonymous ID, verified ID, or session ID.
        /// </summary>
        public Input<string>? SubjectRef
        {
            get => _subjectRef;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _subjectRef = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        public GetSubjectInvokeArgs()
        {
        }
        public static new GetSubjectInvokeArgs Empty => new GetSubjectInvokeArgs();
    }


    [OutputType]
    public sealed class GetSubjectResult
    {
        /// <summary>
        /// The subject's anonymous ID, if any. Secret, because it identifies a person.
        /// </summary>
        public readonly string AnonymousId;
        /// <summary>
        /// Whether Osano knows the subject. The ID outputs are empty when false.
        /// </summary>
        public readonly bool Exists;
        /// <summary>
        /// The subject's Osano ID. Secret, because it identifies a person.
        /// </summary>
        public readonly string SubjectId;
        /// <summary>
        /// The subject reference that was resolved. Secret, because it identifies a person.
        /// </summary>
        public readonly string SubjectRef;
        /// <summary>
        /// The subject's verified ID, if the subject is verified. Secret, because it identifies a person.
        /// </summary>
        public readonly string VerifiedId;

        [OutputConstructor]
        private GetSubjectResult(
            string anonymousId,

            bool exists,

            string subjectId,

            string subjectRef,

            string verifiedId)
        {
            AnonymousId = anonymousId;
            Exists = exists;
            SubjectId = subjectId;
            SubjectRef = subjectRef;
            VerifiedId = verifiedId;
        }
    }
}
