// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Community.Pulumi.Osano
{
    [OsanoResourceType("pulumi:providers:osano")]
    public partial class Provider : global::Pulumi.ProviderResource
    {
        /// <summary>
        /// Base URL of the Unified Consent API, including any path prefix (default https://uc.api.osano.com). The OSANO_API_BASE_URL environment variable is used when it is unset. Must use https, except for loopback hosts.
        /// </summary>
        [Output("apiBaseUrl")]
        public Output<string?> ApiBaseUrl { get; private set; } = null!;

        /// <summary>
        /// Base URL of the Customer REST API (default https://api.osano.com). The OSANO_CUSTOMER_BASE_URL environment variable is used when it is unset. Must use https, except for loopback hosts.
        /// </summary>
        [Output("customerBaseUrl")]
        public Output<string?> CustomerBaseUrl { get; private set; } = null!;

        /// <summary>
        /// Osano Customer REST API key, sent as x-osano-api-key by the Cookie Consent resources and functions and by sendSubjectCode and verifySubjectCode. Set it with `pulumi config set osano:osanoApiKey --secret`; the OSANO_API_KEY environment variable is used when it is unset.
        /// </summary>
        [Output("osanoApiKey")]
        public Output<string?> OsanoApiKey { get; private set; } = null!;

        /// <summary>
        /// Former name of unifiedConsentApiKey, read only when that key is unset.
        /// </summary>
        [Output("ucApiKey")]
        public Output<string?> UcApiKey { get; private set; } = null!;

        /// <summary>
        /// Former name of apiBaseUrl, read only when apiBaseUrl is unset.
        /// </summary>
        [Output("ucBaseUrl")]
        public Output<string?> UcBaseUrl { get; private set; } = null!;

        /// <summary>
        /// Unified Consent API key, sent as x-uc-api-key by the Consent resource and the Unified Consent functions. Set it with `pulumi config set osano:unifiedConsentApiKey --secret`; the OSANO_UC_API_KEY environment variable is used when it is unset.
        /// </summary>
        [Output("unifiedConsentApiKey")]
        public Output<string?> UnifiedConsentApiKey { get; private set; } = null!;


        /// <summary>
        /// Create a Provider resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Provider(string name, ProviderArgs? args = null, CustomResourceOptions? options = null)
            : base("osano", name, args ?? new ProviderArgs(), MakeResourceOptions(options, ""))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/jflavan/pulumi-osano",
                AdditionalSecretOutputs =
                {
                    "osanoApiKey",
                    "ucApiKey",
                    "unifiedConsentApiKey",
                },
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
    }

    public sealed class ProviderArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Base URL of the Unified Consent API, including any path prefix (default https://uc.api.osano.com). The OSANO_API_BASE_URL environment variable is used when it is unset. Must use https, except for loopback hosts.
        /// </summary>
        [Input("apiBaseUrl")]
        public Input<string>? ApiBaseUrl { get; set; }

        /// <summary>
        /// Base URL of the Customer REST API (default https://api.osano.com). The OSANO_CUSTOMER_BASE_URL environment variable is used when it is unset. Must use https, except for loopback hosts.
        /// </summary>
        [Input("customerBaseUrl")]
        public Input<string>? CustomerBaseUrl { get; set; }

        [Input("osanoApiKey")]
        private Input<string>? _osanoApiKey;

        /// <summary>
        /// Osano Customer REST API key, sent as x-osano-api-key by the Cookie Consent resources and functions and by sendSubjectCode and verifySubjectCode. Set it with `pulumi config set osano:osanoApiKey --secret`; the OSANO_API_KEY environment variable is used when it is unset.
        /// </summary>
        public Input<string>? OsanoApiKey
        {
            get => _osanoApiKey;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _osanoApiKey = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// Timeout in seconds for each HTTP request attempt to the Osano APIs, from 1 to 3600 (default 60). Retried requests wait for each attempt separately. The OSANO_API_TIMEOUT_SECONDS environment variable is used when it is unset.
        /// </summary>
        [Input("requestTimeoutSeconds", json: true)]
        public Input<int>? RequestTimeoutSeconds { get; set; }

        [Input("ucApiKey")]
        private Input<string>? _ucApiKey;

        /// <summary>
        /// Former name of unifiedConsentApiKey, read only when that key is unset.
        /// </summary>
        [Obsolete(@"use unifiedConsentApiKey instead")]
        public Input<string>? UcApiKey
        {
            get => _ucApiKey;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _ucApiKey = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// Former name of apiBaseUrl, read only when apiBaseUrl is unset.
        /// </summary>
        [Input("ucBaseUrl")]
        public Input<string>? UcBaseUrl { get; set; }

        [Input("unifiedConsentApiKey")]
        private Input<string>? _unifiedConsentApiKey;

        /// <summary>
        /// Unified Consent API key, sent as x-uc-api-key by the Consent resource and the Unified Consent functions. Set it with `pulumi config set osano:unifiedConsentApiKey --secret`; the OSANO_UC_API_KEY environment variable is used when it is unset.
        /// </summary>
        public Input<string>? UnifiedConsentApiKey
        {
            get => _unifiedConsentApiKey;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _unifiedConsentApiKey = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        public ProviderArgs()
        {
        }
        public static new ProviderArgs Empty => new ProviderArgs();
    }
}
