// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Community.Pulumi.Osano
{
    public static class SendSubjectCode
    {
        /// <summary>
        /// Sends a verification code to a subject's email or phone, authenticating with every configured key (the Osano API key, the Unified Consent API key, or both). Pulumi runs invokes on every preview, update, and refresh, so declaring this in a stack sends a new code each time; call it from automation rather than from long-lived stack code.
        /// </summary>
        public static Task<SendSubjectCodeResult> InvokeAsync(SendSubjectCodeArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<SendSubjectCodeResult>("osano:index:sendSubjectCode", args ?? new SendSubjectCodeArgs(), options.WithDefaults());

        /// <summary>
        /// Sends a verification code to a subject's email or phone, authenticating with every configured key (the Osano API key, the Unified Consent API key, or both). Pulumi runs invokes on every preview, update, and refresh, so declaring this in a stack sends a new code each time; call it from automation rather than from long-lived stack code.
        /// </summary>
        public static Output<SendSubjectCodeResult> Invoke(SendSubjectCodeInvokeArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<SendSubjectCodeResult>("osano:index:sendSubjectCode", args ?? new SendSubjectCodeInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// Sends a verification code to a subject's email or phone, authenticating with every configured key (the Osano API key, the Unified Consent API key, or both). Pulumi runs invokes on every preview, update, and refresh, so declaring this in a stack sends a new code each time; call it from automation rather than from long-lived stack code.
        /// </summary>
        public static Output<SendSubjectCodeResult> Invoke(SendSubjectCodeInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<SendSubjectCodeResult>("osano:index:sendSubjectCode", args ?? new SendSubjectCodeInvokeArgs(), options.WithDefaults());
    }


    public sealed class SendSubjectCodeArgs : global::Pulumi.InvokeArgs
    {
        [Input("email")]
        private string? _email;

        /// <summary>
        /// Email address to send the code to. Set exactly one of email or phone. Secret, because it is personal data.
        /// </summary>
        public string? Email
        {
            get => _email;
            set => _email = value;
        }

        /// <summary>
        /// Optional hashed subject identifier, sent only when set. Osano's current API identifies the subject by email or phone.
        /// </summary>
        [Input("hashedSubjectId")]
        public string? HashedSubjectId { get; set; }

        [Input("phone")]
        private string? _phone;

        /// <summary>
        /// Phone number to send the code to by SMS. Set exactly one of email or phone. Secret, because it is personal data.
        /// </summary>
        public string? Phone
        {
            get => _phone;
            set => _phone = value;
        }

        public SendSubjectCodeArgs()
        {
        }
        public static new SendSubjectCodeArgs Empty => new SendSubjectCodeArgs();
    }

    public sealed class SendSubjectCodeInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("email")]
        private Input<string>? _email;

        /// <summary>
        /// Email address to send the code to. Set exactly one of email or phone. Secret, because it is personal data.
        /// </summary>
        public Input<string>? Email
        {
            get => _email;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _email = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// Optional hashed subject identifier, sent only when set. Osano's current API identifies the subject by email or phone.
        /// </summary>
        [Input("hashedSubjectId")]
        public Input<string>? HashedSubjectId { get; set; }

        [Input("phone")]
        private Input<string>? _phone;

        /// <summary>
        /// Phone number to send the code to by SMS. Set exactly one of email or phone. Secret, because it is personal data.
        /// </summary>
        public Input<string>? Phone
        {
            get => _phone;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _phone = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        public SendSubjectCodeInvokeArgs()
        {
        }
        public static new SendSubjectCodeInvokeArgs Empty => new SendSubjectCodeInvokeArgs();
    }


    [OutputType]
    public sealed class SendSubjectCodeResult
    {
        /// <summary>
        /// The delivery channel: email or sms.
        /// </summary>
        public readonly string Channel;
        /// <summary>
        /// The email address or phone number the code was sent to. Secret, because it is personal data.
        /// </summary>
        public readonly string Destination;
        /// <summary>
        /// The hashed subject identifier sent with the request, if any.
        /// </summary>
        public readonly string HashedSubjectId;
        /// <summary>
        /// The SMS challenge session, when Osano returns one; pass it to verifySubjectCode. Empty for email.
        /// </summary>
        public readonly string Session;

        [OutputConstructor]
        private SendSubjectCodeResult(
            string channel,

            string destination,

            string hashedSubjectId,

            string session)
        {
            Channel = channel;
            Destination = destination;
            HashedSubjectId = hashedSubjectId;
            Session = session;
        }
    }
}
