# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities

import types

__config__ = pulumi.Config('osano')


class _ExportableConfig(types.ModuleType):
    @_builtins.property
    def api_base_url(self) -> Optional[str]:
        """
        Base URL of the Unified Consent API, including any path prefix (default https://uc.api.osano.com). The OSANO_API_BASE_URL environment variable is used when it is unset. Must use https, except for loopback hosts.
        """
        return __config__.get('apiBaseUrl')

    @_builtins.property
    def customer_base_url(self) -> Optional[str]:
        """
        Base URL of the Customer REST API (default https://api.osano.com). The OSANO_CUSTOMER_BASE_URL environment variable is used when it is unset. Must use https, except for loopback hosts.
        """
        return __config__.get('customerBaseUrl')

    @_builtins.property
    def osano_api_key(self) -> Optional[str]:
        """
        Osano Customer REST API key, sent as x-osano-api-key by the Cookie Consent resources and functions and by sendSubjectCode and verifySubjectCode. Set it with `pulumi config set osano:osanoApiKey --secret`; the OSANO_API_KEY environment variable is used when it is unset.
        """
        return __config__.get('osanoApiKey')

    @_builtins.property
    def request_timeout_seconds(self) -> Optional[int]:
        """
        Timeout in seconds for each HTTP request attempt to the Osano APIs, from 1 to 3600 (default 60). Retried requests wait for each attempt separately. The OSANO_API_TIMEOUT_SECONDS environment variable is used when it is unset.
        """
        return __config__.get_int('requestTimeoutSeconds')

    @_builtins.property
    def uc_api_key(self) -> Optional[str]:
        """
        Former name of unifiedConsentApiKey, read only when that key is unset.
        """
        return __config__.get('ucApiKey')

    @_builtins.property
    def uc_base_url(self) -> Optional[str]:
        """
        Former name of apiBaseUrl, read only when apiBaseUrl is unset.
        """
        return __config__.get('ucBaseUrl')

    @_builtins.property
    def unified_consent_api_key(self) -> Optional[str]:
        """
        Unified Consent API key, sent as x-uc-api-key by the Consent resource and the Unified Consent functions. Set it with `pulumi config set osano:unifiedConsentApiKey --secret`; the OSANO_UC_API_KEY environment variable is used when it is unset.
        """
        return __config__.get('unifiedConsentApiKey')
