// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

/**
 * One consent decision: the subject's action for a privacy protocol within a configuration.
 */
export interface ConsentActionArgs {
    /**
     * The subject's choice: ACCEPT, REJECT, or UNSELECTED.
     */
    action: pulumi.Input<string>;
    /**
     * Optional jurisdiction for this action; overrides the top-level jurisdiction.
     */
    jurisdiction?: pulumi.Input<string | undefined>;
    /**
     * The privacy protocol ID (the Target ID on the privacy protocol's edit page).
     */
    target: pulumi.Input<string>;
    /**
     * The Unified Consent configuration ID the consent is recorded for.
     */
    vendor: pulumi.Input<string>;
}

/**
 * Compliance metadata recorded with a consent: the privacy policy in effect and the GPC signal.
 */
export interface ConsentComplianceArgs {
    /**
     * 1 if the Global Privacy Control signal is enabled, 0 otherwise.
     */
    gpc?: pulumi.Input<number | undefined>;
    /**
     * The privacy policy in effect when the consent was given.
     */
    privacyPolicy?: pulumi.Input<inputs.ConsentPrivacyPolicyArgs | undefined>;
}

/**
 * The published privacy policy a consent was given under.
 */
export interface ConsentPrivacyPolicyArgs {
    /**
     * The privacy policy URL.
     */
    url: pulumi.Input<string>;
    /**
     * The privacy policy version active when the consent was submitted.
     */
    version?: pulumi.Input<string | undefined>;
}

/**
 * The subject a consent is recorded for, identified by a verified ID or an anonymous ID.
 */
export interface ConsentSubjectArgs {
    /**
     * The subject's anonymous ID. Must not contain #, %, or spaces.
     */
    anonymousId?: pulumi.Input<string | undefined>;
    /**
     * The subject's verified ID. Must not contain #, %, or spaces.
     */
    verifiedId?: pulumi.Input<string | undefined>;
}

