// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package osano

import (
	"context"
	"reflect"

	"github.com/jflavan/pulumi-osano/sdk/go/osano/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type Provider struct {
	pulumi.ProviderResourceState

	// Base URL of the Unified Consent API, including any path prefix (default https://uc.api.osano.com). The OSANO_API_BASE_URL environment variable is used when it is unset. Must use https, except for loopback hosts.
	ApiBaseUrl pulumi.StringPtrOutput `pulumi:"apiBaseUrl"`
	// Base URL of the Customer REST API (default https://api.osano.com). The OSANO_CUSTOMER_BASE_URL environment variable is used when it is unset. Must use https, except for loopback hosts.
	CustomerBaseUrl pulumi.StringPtrOutput `pulumi:"customerBaseUrl"`
	// Osano Customer REST API key, sent as x-osano-api-key by the Cookie Consent resources and functions and by sendSubjectCode and verifySubjectCode. Set it with `pulumi config set osano:osanoApiKey --secret`; the OSANO_API_KEY environment variable is used when it is unset.
	OsanoApiKey pulumi.StringPtrOutput `pulumi:"osanoApiKey"`
	// Former name of unifiedConsentApiKey, read only when that key is unset.
	//
	// Deprecated: use unifiedConsentApiKey instead
	UcApiKey pulumi.StringPtrOutput `pulumi:"ucApiKey"`
	// Former name of apiBaseUrl, read only when apiBaseUrl is unset.
	//
	// Deprecated: use apiBaseUrl instead
	UcBaseUrl pulumi.StringPtrOutput `pulumi:"ucBaseUrl"`
	// Unified Consent API key, sent as x-uc-api-key by the Consent resource and the Unified Consent functions. Set it with `pulumi config set osano:unifiedConsentApiKey --secret`; the OSANO_UC_API_KEY environment variable is used when it is unset.
	UnifiedConsentApiKey pulumi.StringPtrOutput `pulumi:"unifiedConsentApiKey"`
}

// NewProvider registers a new resource with the given unique name, arguments, and options.
func NewProvider(ctx *pulumi.Context,
	name string, args *ProviderArgs, opts ...pulumi.ResourceOption) (*Provider, error) {
	if args == nil {
		args = &ProviderArgs{}
	}

	if args.OsanoApiKey != nil {
		args.OsanoApiKey = pulumi.ToSecret(args.OsanoApiKey).(pulumi.StringPtrInput)
	}
	if args.UcApiKey != nil {
		args.UcApiKey = pulumi.ToSecret(args.UcApiKey).(pulumi.StringPtrInput)
	}
	if args.UnifiedConsentApiKey != nil {
		args.UnifiedConsentApiKey = pulumi.ToSecret(args.UnifiedConsentApiKey).(pulumi.StringPtrInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"osanoApiKey",
		"ucApiKey",
		"unifiedConsentApiKey",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Provider
	err := ctx.RegisterResource("pulumi:providers:osano", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

type providerArgs struct {
	// Base URL of the Unified Consent API, including any path prefix (default https://uc.api.osano.com). The OSANO_API_BASE_URL environment variable is used when it is unset. Must use https, except for loopback hosts.
	ApiBaseUrl *string `pulumi:"apiBaseUrl"`
	// Base URL of the Customer REST API (default https://api.osano.com). The OSANO_CUSTOMER_BASE_URL environment variable is used when it is unset. Must use https, except for loopback hosts.
	CustomerBaseUrl *string `pulumi:"customerBaseUrl"`
	// Osano Customer REST API key, sent as x-osano-api-key by the Cookie Consent resources and functions and by sendSubjectCode and verifySubjectCode. Set it with `pulumi config set osano:osanoApiKey --secret`; the OSANO_API_KEY environment variable is used when it is unset.
	OsanoApiKey *string `pulumi:"osanoApiKey"`
	// Timeout in seconds for each HTTP request attempt to the Osano APIs, from 1 to 3600 (default 60). Retried requests wait for each attempt separately. The OSANO_API_TIMEOUT_SECONDS environment variable is used when it is unset.
	RequestTimeoutSeconds *int `pulumi:"requestTimeoutSeconds"`
	// Former name of unifiedConsentApiKey, read only when that key is unset.
	//
	// Deprecated: use unifiedConsentApiKey instead
	UcApiKey *string `pulumi:"ucApiKey"`
	// Former name of apiBaseUrl, read only when apiBaseUrl is unset.
	//
	// Deprecated: use apiBaseUrl instead
	UcBaseUrl *string `pulumi:"ucBaseUrl"`
	// Unified Consent API key, sent as x-uc-api-key by the Consent resource and the Unified Consent functions. Set it with `pulumi config set osano:unifiedConsentApiKey --secret`; the OSANO_UC_API_KEY environment variable is used when it is unset.
	UnifiedConsentApiKey *string `pulumi:"unifiedConsentApiKey"`
}

// The set of arguments for constructing a Provider resource.
type ProviderArgs struct {
	// Base URL of the Unified Consent API, including any path prefix (default https://uc.api.osano.com). The OSANO_API_BASE_URL environment variable is used when it is unset. Must use https, except for loopback hosts.
	ApiBaseUrl pulumi.StringPtrInput
	// Base URL of the Customer REST API (default https://api.osano.com). The OSANO_CUSTOMER_BASE_URL environment variable is used when it is unset. Must use https, except for loopback hosts.
	CustomerBaseUrl pulumi.StringPtrInput
	// Osano Customer REST API key, sent as x-osano-api-key by the Cookie Consent resources and functions and by sendSubjectCode and verifySubjectCode. Set it with `pulumi config set osano:osanoApiKey --secret`; the OSANO_API_KEY environment variable is used when it is unset.
	OsanoApiKey pulumi.StringPtrInput
	// Timeout in seconds for each HTTP request attempt to the Osano APIs, from 1 to 3600 (default 60). Retried requests wait for each attempt separately. The OSANO_API_TIMEOUT_SECONDS environment variable is used when it is unset.
	RequestTimeoutSeconds pulumi.IntPtrInput
	// Former name of unifiedConsentApiKey, read only when that key is unset.
	//
	// Deprecated: use unifiedConsentApiKey instead
	UcApiKey pulumi.StringPtrInput
	// Former name of apiBaseUrl, read only when apiBaseUrl is unset.
	//
	// Deprecated: use apiBaseUrl instead
	UcBaseUrl pulumi.StringPtrInput
	// Unified Consent API key, sent as x-uc-api-key by the Consent resource and the Unified Consent functions. Set it with `pulumi config set osano:unifiedConsentApiKey --secret`; the OSANO_UC_API_KEY environment variable is used when it is unset.
	UnifiedConsentApiKey pulumi.StringPtrInput
}

func (ProviderArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*providerArgs)(nil)).Elem()
}

type ProviderInput interface {
	pulumi.Input

	ToProviderOutput() ProviderOutput
	ToProviderOutputWithContext(ctx context.Context) ProviderOutput
}

func (*Provider) ElementType() reflect.Type {
	return reflect.TypeOf((**Provider)(nil)).Elem()
}

func (i *Provider) ToProviderOutput() ProviderOutput {
	return i.ToProviderOutputWithContext(context.Background())
}

func (i *Provider) ToProviderOutputWithContext(ctx context.Context) ProviderOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ProviderOutput)
}

type ProviderOutput struct{ *pulumi.OutputState }

func (ProviderOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Provider)(nil)).Elem()
}

func (o ProviderOutput) ToProviderOutput() ProviderOutput {
	return o
}

func (o ProviderOutput) ToProviderOutputWithContext(ctx context.Context) ProviderOutput {
	return o
}

// Base URL of the Unified Consent API, including any path prefix (default https://uc.api.osano.com). The OSANO_API_BASE_URL environment variable is used when it is unset. Must use https, except for loopback hosts.
func (o ProviderOutput) ApiBaseUrl() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.ApiBaseUrl }).(pulumi.StringPtrOutput)
}

// Base URL of the Customer REST API (default https://api.osano.com). The OSANO_CUSTOMER_BASE_URL environment variable is used when it is unset. Must use https, except for loopback hosts.
func (o ProviderOutput) CustomerBaseUrl() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.CustomerBaseUrl }).(pulumi.StringPtrOutput)
}

// Osano Customer REST API key, sent as x-osano-api-key by the Cookie Consent resources and functions and by sendSubjectCode and verifySubjectCode. Set it with `pulumi config set osano:osanoApiKey --secret`; the OSANO_API_KEY environment variable is used when it is unset.
func (o ProviderOutput) OsanoApiKey() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.OsanoApiKey }).(pulumi.StringPtrOutput)
}

// Former name of unifiedConsentApiKey, read only when that key is unset.
//
// Deprecated: use unifiedConsentApiKey instead
func (o ProviderOutput) UcApiKey() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.UcApiKey }).(pulumi.StringPtrOutput)
}

// Former name of apiBaseUrl, read only when apiBaseUrl is unset.
//
// Deprecated: use apiBaseUrl instead
func (o ProviderOutput) UcBaseUrl() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.UcBaseUrl }).(pulumi.StringPtrOutput)
}

// Unified Consent API key, sent as x-uc-api-key by the Consent resource and the Unified Consent functions. Set it with `pulumi config set osano:unifiedConsentApiKey --secret`; the OSANO_UC_API_KEY environment variable is used when it is unset.
func (o ProviderOutput) UnifiedConsentApiKey() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.UnifiedConsentApiKey }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ProviderInput)(nil)).Elem(), &Provider{})
	pulumi.RegisterOutputType(ProviderOutput{})
}
