// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Lists the classification rules of a Cookie Consent configuration, optionally filtered by storage type and classification. Useful for auditing rules managed outside Pulumi or finding rule IDs to import.
 */
export function getCookieConsentRules(args: GetCookieConsentRulesArgs, opts?: pulumi.InvokeOptions): Promise<GetCookieConsentRulesResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("osano:index:getCookieConsentRules", {
        "classification": args.classification,
        "configId": args.configId,
        "maxResults": args.maxResults,
        "storeType": args.storeType,
    }, opts);
}

export interface GetCookieConsentRulesArgs {
    /**
     * Only return rules with this classification: ANALYTICS, BLACKLISTED, ESSENTIAL, HIDDEN, MARKETING, PERSONALIZATION.
     */
    classification?: string;
    /**
     * The Osano Cookie Consent config ID whose rules are listed.
     */
    configId: string;
    /**
     * Stop after this many rules. Unset or 0 returns every matching rule.
     */
    maxResults?: number;
    /**
     * Only return rules of this storage type: cookies, scripts, iframes, localStorage.
     */
    storeType?: string;
}

export interface GetCookieConsentRulesResult {
    /**
     * The config ID that was queried.
     */
    readonly configId: string;
    /**
     * Every matching rule, across all pages.
     */
    readonly rules: outputs.CookieConsentRuleDetails[];
}
/**
 * Lists the classification rules of a Cookie Consent configuration, optionally filtered by storage type and classification. Useful for auditing rules managed outside Pulumi or finding rule IDs to import.
 */
export function getCookieConsentRulesOutput(args: GetCookieConsentRulesOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetCookieConsentRulesResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("osano:index:getCookieConsentRules", {
        "classification": args.classification,
        "configId": args.configId,
        "maxResults": args.maxResults,
        "storeType": args.storeType,
    }, opts);
}

export interface GetCookieConsentRulesOutputArgs {
    /**
     * Only return rules with this classification: ANALYTICS, BLACKLISTED, ESSENTIAL, HIDDEN, MARKETING, PERSONALIZATION.
     */
    classification?: pulumi.Input<string | undefined>;
    /**
     * The Osano Cookie Consent config ID whose rules are listed.
     */
    configId: pulumi.Input<string>;
    /**
     * Stop after this many rules. Unset or 0 returns every matching rule.
     */
    maxResults?: pulumi.Input<number | undefined>;
    /**
     * Only return rules of this storage type: cookies, scripts, iframes, localStorage.
     */
    storeType?: pulumi.Input<string | undefined>;
}
