// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class Provider extends pulumi.ProviderResource {
    /** @internal */
    public static readonly __pulumiType = 'osano';

    /**
     * Returns true if the given object is an instance of Provider.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Provider {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === "pulumi:providers:" + Provider.__pulumiType;
    }

    /**
     * Base URL of the Unified Consent API, including any path prefix (default https://uc.api.osano.com). The OSANO_API_BASE_URL environment variable is used when it is unset. Must use https, except for loopback hosts.
     */
    declare public readonly apiBaseUrl: pulumi.Output<string | undefined>;
    /**
     * Base URL of the Customer REST API (default https://api.osano.com). The OSANO_CUSTOMER_BASE_URL environment variable is used when it is unset. Must use https, except for loopback hosts.
     */
    declare public readonly customerBaseUrl: pulumi.Output<string | undefined>;
    /**
     * Osano Customer REST API key, sent as x-osano-api-key by the Cookie Consent resources and functions and by sendSubjectCode and verifySubjectCode. Set it with `pulumi config set osano:osanoApiKey --secret`; the OSANO_API_KEY environment variable is used when it is unset.
     */
    declare public readonly osanoApiKey: pulumi.Output<string | undefined>;
    /**
     * Former name of unifiedConsentApiKey, read only when that key is unset.
     *
     * @deprecated use unifiedConsentApiKey instead
     */
    declare public readonly ucApiKey: pulumi.Output<string | undefined>;
    /**
     * Former name of apiBaseUrl, read only when apiBaseUrl is unset.
     *
     * @deprecated use apiBaseUrl instead
     */
    declare public readonly ucBaseUrl: pulumi.Output<string | undefined>;
    /**
     * Unified Consent API key, sent as x-uc-api-key by the Consent resource and the Unified Consent functions. Set it with `pulumi config set osano:unifiedConsentApiKey --secret`; the OSANO_UC_API_KEY environment variable is used when it is unset.
     */
    declare public readonly unifiedConsentApiKey: pulumi.Output<string | undefined>;

    /**
     * Create a Provider resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: ProviderArgs, opts?: pulumi.ResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        {
            resourceInputs["apiBaseUrl"] = args?.apiBaseUrl;
            resourceInputs["customerBaseUrl"] = args?.customerBaseUrl;
            resourceInputs["osanoApiKey"] = args?.osanoApiKey ? pulumi.secret(args.osanoApiKey) : undefined;
            resourceInputs["requestTimeoutSeconds"] = pulumi.output(args?.requestTimeoutSeconds).apply(JSON.stringify);
            resourceInputs["ucApiKey"] = args?.ucApiKey ? pulumi.secret(args.ucApiKey) : undefined;
            resourceInputs["ucBaseUrl"] = args?.ucBaseUrl;
            resourceInputs["unifiedConsentApiKey"] = args?.unifiedConsentApiKey ? pulumi.secret(args.unifiedConsentApiKey) : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["osanoApiKey", "ucApiKey", "unifiedConsentApiKey"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(Provider.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Provider resource.
 */
export interface ProviderArgs {
    /**
     * Base URL of the Unified Consent API, including any path prefix (default https://uc.api.osano.com). The OSANO_API_BASE_URL environment variable is used when it is unset. Must use https, except for loopback hosts.
     */
    apiBaseUrl?: pulumi.Input<string | undefined>;
    /**
     * Base URL of the Customer REST API (default https://api.osano.com). The OSANO_CUSTOMER_BASE_URL environment variable is used when it is unset. Must use https, except for loopback hosts.
     */
    customerBaseUrl?: pulumi.Input<string | undefined>;
    /**
     * Osano Customer REST API key, sent as x-osano-api-key by the Cookie Consent resources and functions and by sendSubjectCode and verifySubjectCode. Set it with `pulumi config set osano:osanoApiKey --secret`; the OSANO_API_KEY environment variable is used when it is unset.
     */
    osanoApiKey?: pulumi.Input<string | undefined>;
    /**
     * Timeout in seconds for each HTTP request attempt to the Osano APIs, from 1 to 3600 (default 60). Retried requests wait for each attempt separately. The OSANO_API_TIMEOUT_SECONDS environment variable is used when it is unset.
     */
    requestTimeoutSeconds?: pulumi.Input<number | undefined>;
    /**
     * Former name of unifiedConsentApiKey, read only when that key is unset.
     *
     * @deprecated use unifiedConsentApiKey instead
     */
    ucApiKey?: pulumi.Input<string | undefined>;
    /**
     * Former name of apiBaseUrl, read only when apiBaseUrl is unset.
     *
     * @deprecated use apiBaseUrl instead
     */
    ucBaseUrl?: pulumi.Input<string | undefined>;
    /**
     * Unified Consent API key, sent as x-uc-api-key by the Consent resource and the Unified Consent functions. Set it with `pulumi config set osano:unifiedConsentApiKey --secret`; the OSANO_UC_API_KEY environment variable is used when it is unset.
     */
    unifiedConsentApiKey?: pulumi.Input<string | undefined>;
}
